const data = [
    {
        id:30021,
        name:"طرح درس سالانه ریاضی پایه سوم",
        caption:"طرح درس سالانه ریاضی پایه سوم - منطبق با آخرین ویرایش کتب درسی",

        creator:"جناب آقای لبافی",
        upoledDate:"1403/08/18",
        fileType:"WORD",
        src:"/Files/hamyar/sevom/tarhedars/101.doc",
        book:"riazi",
        boolInP:"ریاضی",
        gradeInP:"پایه سوم",
        image:"/images/hamyar/components/modules/books/sevom/riazi.jpg",
        slug: "/hamyar/sevom/tarhedars/30021"
    }
    ,
    {
        id:30022,
        name:"طرح درس سالانه علوم تجربی سوم",
        caption:"طرح درس سالانه علوم تجربی پایه سوم - منطبق با آخرین ویرایش کتب درسی",
        creator:"جناب آقای لبافی",
        upoledDate:"1403/08/18",
        fileType:"WORD",
        src:"/Files/hamyar/sevom/tarhedars/102.docx",
        book:"oloom",
        boolInP:"علوم تجربی",
        gradeInP:"پایه سوم",
        image:"/images/hamyar/components/modules/books/sevom/oloom.jpg",
        slug: "/hamyar/sevom/tarhedars/30022"
    }
    ,
    {
        id:30023,
        name:"طرح درس سالانه مطالعات اجتماعی سوم",
        caption:"طرح درس سالانه مطالعات اجتماعی پایه سوم - منطبق با آخرین ویرایش کتب درسی",
        creator:"جناب آقای لبافی",
        upoledDate:"1403/08/18",
        fileType:"WORD",
        src:"/Files/hamyar/sevom/tarhedars/103.doc",
        book:"motaleat",
        boolInP:"مطالعات اجتماعی",
        gradeInP:"پایه سوم",
        image:"/images/hamyar/components/modules/books/sevom/motaleat.jpg",
        slug: "/hamyar/sevom/tarhedars/30023"
    }
    ,
    {
        id:30024,
        name:"طرح درس سالانه هدیه های آسمانی سوم",
        caption:"طرح درس سالانه هدیه های آسمانی پایه سوم - منطبق با آخرین ویرایش کتب درسی",
        creator:"جناب آقای لبافی",
        upoledDate:"1403/08/18",
        fileType:"WORD",
        src:"/Files/hamyar/sevom/tarhedars/104.doc",
        book:"hedye",
        boolInP:"هدیه های آسمانی",
        gradeInP:"پایه سوم",
        image:"/images/hamyar/components/modules/books/sevom/hedye.jpg",
        slug: "/hamyar/sevom/tarhedars/30024"
    }
    ,
    {
        id:30025,
        name:"طرح درس سالانه آموزش قرآن سوم",
        caption:"طرح درس سالانه آموزش قرآن پایه سوم - منطبق با آخرین ویرایش کتب درسی",
        creator:"جناب آقای لبافی",
        upoledDate:"1403/08/18",
        fileType:"WORD",
        src:"/Files/hamyar/sevom/tarhedars/105.doc",
        book:"quran",
        boolInP:"آموزش قرآن",
        gradeInP:"پایه سوم",
        image:"/images/hamyar/components/modules/books/sevom/quran.jpg",
        slug: "/hamyar/sevom/tarhedars/30025"
    }    , {
        id:30026,
        name:"طرح درس 7 کار نیک فارسی",
        caption:"طرح درس 7 کار نیک فارسی - سوم دبستان",
        creator:"جناب آقای لبافی",
        upoledDate:"1403/08/21",
        fileType:"PDF",
        src:"/Files/hamyar/sevom/tarhedars/",
        book:"farsi",
        boolInP:"فارسی",
        gradeInP:"پایه سوم",
        image:"/images/hamyar/components/modules/books/sevom/farsi.jpg",
        slug: "/hamyar/sevom/tarhedars/30026"
    },
    {
        "id": 65786,
        "name": "طرح درس روزانه  گفت و گو با خدا هدیه های آسمانی",
        "caption": "طرح درس روزانه  گفت و گو با خدا هدیه های آسمانی - پایه سوم",
        "creator": "سرکار خانم امراللهی",
        "upoledDate": "1403/11/24",
        "fileType": "PDF",
        "src": "https://coding-lbf.storage.iran.liara.space/sevom/amrollahi/06/%D8%B7%D8%B1%D8%AD%20%D8%AF%D8%B1%D8%B3%20%D8%B1%D9%88%D8%B2%D8%A7%D9%86%D9%87%20%20%DA%AF%D9%81%D8%AA%20%D9%88%20%DA%AF%D9%88%20%D8%A8%D8%A7%20%D8%AE%D8%AF%D8%A7%20%D9%87%D8%AF%DB%8C%D9%87%20%D9%87%D8%A7%DB%8C%20%D8%A2%D8%B3%D9%85%D8%A7%D9%86%DB%8C.pdf",
        "book": "hedye",
        "boolInP": "هدیه های آسمان",
        "gradeInP": "پایه سوم",
        "category": "tarhedars",
        "image": "/images/hamyar/components/modules/books/sevom/hedye.jpg",
        "slug": "/hamyar/sevom/tarhedars/65786"
      },
      {
        "id": 18773,
        "name": "طرح درس روزانه آموزش مبحث محیط",
        "caption": "طرح درس روزانه آموزش مبحث محیط - پایه سوم",
        "creator": "سرکار خانم امراللهی",
        "upoledDate": "1403/11/24",
        "fileType": "PDF",
        "src": "https://coding-lbf.storage.iran.liara.space/sevom/amrollahi/06/%D8%B7%D8%B1%D8%AD%20%D8%AF%D8%B1%D8%B3%20%D8%B1%D9%88%D8%B2%D8%A7%D9%86%D9%87%20%D8%A2%D9%85%D9%88%D8%B2%D8%B4%20%D9%85%D8%A8%D8%AD%D8%AB%20%D9%85%D8%AD%DB%8C%D8%B7.pdf",
        "book": "riazi",
        "boolInP": "ریاضی",
        "gradeInP": "پایه سوم",
        "category": "tarhedars",
        "image": "/images/hamyar/components/modules/books/sevom/riazi.jpg",
        "slug": "/hamyar/sevom/tarhedars/18773"
      },
      {
        "id": 88728,
        "name": "طرح درس روزانه بازیافت  مطالعات اجتماعی",
        "caption": "طرح درس روزانه بازیافت  مطالعات اجتماعی - پایه سوم",
        "creator": "سرکار خانم امراللهی",
        "upoledDate": "1403/11/24",
        "fileType": "PDF",
        "src": "https://coding-lbf.storage.iran.liara.space/sevom/amrollahi/06/%D8%B7%D8%B1%D8%AD%20%D8%AF%D8%B1%D8%B3%20%D8%B1%D9%88%D8%B2%D8%A7%D9%86%D9%87%20%D8%A8%D8%A7%D8%B2%DB%8C%D8%A7%D9%81%D8%AA%20%20%D9%85%D8%B7%D8%A7%D9%84%D8%B9%D8%A7%D8%AA%20%D8%A7%D8%AC%D8%AA%D9%85%D8%A7%D8%B9%DB%8C.pdf",
        "book": "motaleat",
        "boolInP": "مطالعات اجتماعی",
        "gradeInP": "پایه سوم",
        "category": "tarhedars",
        "image": "/images/hamyar/components/modules/books/sevom/motaleat.jpg",
        "slug": "/hamyar/sevom/tarhedars/88728"
      },
      {
        "id": 28078,
        "name": "طرح درس روزانه کار نیک  فارسی",
        "caption": "طرح درس روزانه کار نیک  فارسی - پایه سوم",
        "creator": "سرکار خانم امراللهی",
        "upoledDate": "1403/11/24",
        "fileType": "PDF",
        "src": "https://coding-lbf.storage.iran.liara.space/sevom/amrollahi/06/%D8%B7%D8%B1%D8%AD%20%D8%AF%D8%B1%D8%B3%20%D8%B1%D9%88%D8%B2%D8%A7%D9%86%D9%87%20%D9%81%D8%AF%D8%A7%DA%A9%D8%A7%D8%B1%D8%A7%D9%86%20%D9%81%D8%A7%D8%B1%D8%B3%DB%8C.pdf",
        "book": "farsi",
        "boolInP": "فارسی",
        "gradeInP": "پایه سوم",
        "category": "tarhedars",
        "image": "/images/hamyar/components/modules/books/sevom/farsi.jpg",
        "slug": "/hamyar/sevom/tarhedars/28078"
      },
      {
        "id": 98489,
        "name": "طرح درس روزانه فداکاران فارسی",
        "caption": "طرح درس روزانه فداکاران فارسی - پایه سوم",
        "creator": "سرکار خانم امراللهی",
        "upoledDate": "1403/11/24",
        "fileType": "PDF",
        "src": "https://coding-lbf.storage.iran.liara.space/sevom/amrollahi/06/%D8%B7%D8%B1%D8%AD%20%D8%AF%D8%B1%D8%B3%20%D8%B1%D9%88%D8%B2%D8%A7%D9%86%D9%87%20%D9%81%D8%AF%D8%A7%DA%A9%D8%A7%D8%B1%D8%A7%D9%86%20%D9%81%D8%A7%D8%B1%D8%B3%DB%8C.pdf",
        "book": "farsi",
        "boolInP": "فارسی",
        "gradeInP": "پایه سوم",
        "category": "tarhedars",
        "image": "/images/hamyar/components/modules/books/chaharom/farsi.jpg",
        "slug": "/hamyar/sevom/tarhedars/98489"
      },
      {
        "id": 12520,
        "name": "طرح درس علوم درس ۱۱",
        "caption": "طرح درس علوم درس ۱۱ - پایه سوم",
        "creator": "سرکار خانم امراللهی",
        "upoledDate": "1404/02/07",
        "fileType": "PDF",
        "src": "https://coding-lbf.storage.iran.liara.space/sevom/amrollahi/9/%D8%B7%D8%B1%D8%AD%20%D8%AF%D8%B1%D8%B3%20%D8%B9%D9%84%D9%88%D9%85%20%D8%AF%D8%B1%D8%B3%20%DB%B1%DB%B1.pdf",
        "book": "oloom",
        "boolInP": "علوم تجربی",
        "gradeInP": "پایه سوم",
        "category": "tarhedars",
        "image": "/images/hamyar/components/modules/books/sevom/oloom.jpg",
        "slug": "/hamyar/sevom/tarhedars/12520"
      },
      {
        "id": 41204,
        "name": "طرح درس روزانه فارسی،درس دریا",
        "caption": "طرح درس روزانه فارسی،درس دریا - پایه سوم",
        "creator": "سرکار خانم مرادی پور",
        "upoledDate": "1404/02/07",
        "fileType": "PDF",
        "src": "https://coding-lbf.storage.iran.liara.space/sevom/moradi/09/%D8%B7%D8%B1%D8%AD%20%D8%AF%D8%B1%D8%B3%20%D8%B1%D9%88%D8%B2%D8%A7%D9%86%D9%87%20%D9%81%D8%A7%D8%B1%D8%B3%DB%8C%D8%8C%D8%AF%D8%B1%D8%B3%20%D8%AF%D8%B1%DB%8C%D8%A7.pdf",
        "book": "farsi",
        "boolInP": "فارسی",
        "gradeInP": "پایه سوم",
        "category": "tarhedars",
        "image": "/images/hamyar/components/modules/books/sevom/farsi.jpg",
        "slug": "/hamyar/sevom/tarhedars/41204"
      },
      {
        "id": 46226,
        "name": "طرح درس روزانه علوم، درس آب ماده ی با ارزش",
        "caption": "طرح درس روزانه علوم، درس آب ماده ی با ارزش - پایه سوم",
        "creator": "سرکار خانم مرادی پور",
        "upoledDate": "1404/02/07",
        "fileType": "PDF",
        "src": "https://coding-lbf.storage.iran.liara.space/sevom/moradi/09/%D8%B7%D8%B1%D8%AD_%D8%AF%D8%B1%D8%B3_%D8%B1%D9%88%D8%B2%D8%A7%D9%86%D9%87_%D8%B9%D9%84%D9%88%D9%85%D8%8C_%D8%AF%D8%B1%D8%B3_%D8%A2%D8%A8_%D9%85%D8%A7%D8%AF%D9%87_%DB%8C_%D8%A8%D8%A7_%D8%A7%D8%B1%D8%B2%D8%B4.pdf",
        "book": "oloom",
        "boolInP": "علوم تجربی",
        "gradeInP": "پایه سوم",
        "category": "tarhedars",
        "image": "/images/hamyar/components/modules/books/sevom/oloom.jpg",
        "slug": "/hamyar/sevom/tarhedars/46226"
      },
      {
        "id": 54941,
        "name": "طرح درس روزانه ریاضی، درس کسر",
        "caption": "طرح درس روزانه ریاضی، درس کسر - پایه سوم",
        "creator": "سرکار خانم مرادی پور",
        "upoledDate": "1404/02/07",
        "fileType": "PDF",
        "src": "https://coding-lbf.storage.iran.liara.space/sevom/moradi/09/%D8%B7%D8%B1%D8%AD%20%D8%AF%D8%B1%D8%B3%20%D8%B1%D9%88%D8%B2%D8%A7%D9%86%D9%87%20%D8%B1%DB%8C%D8%A7%D8%B6%DB%8C%D8%8C%20%D8%AF%D8%B1%D8%B3%20%DA%A9%D8%B3%D8%B1.pdf",
        "book": "riazi",
        "boolInP": "ریاضی",
        "gradeInP": "پایه سوم",
        "category": "tarhedars",
        "image": "/images/hamyar/components/modules/books/sevom/riazi.jpg",
        "slug": "/hamyar/sevom/tarhedars/54941"
      },
      {
        "id": 32552,
        "name": "طرح درس روزانه مطالعات،درس بازیافت ",
        "caption": "طرح درس روزانه مطالعات،درس بازیافت  - پایه سوم",
        "creator": "سرکار خانم مرادی پور",
        "upoledDate": "1404/02/07",
        "fileType": "PDF",
        "src": "https://coding-lbf.storage.iran.liara.space/sevom/moradi/09/%D8%B7%D8%B1%D8%AD%20%D8%AF%D8%B1%D8%B3%20%D8%B1%D9%88%D8%B2%D8%A7%D9%86%D9%87%20%D9%85%D8%B7%D8%A7%D9%84%D8%B9%D8%A7%D8%AA%D8%8C%D8%AF%D8%B1%D8%B3%20%D8%A8%D8%A7%D8%B2%DB%8C%D8%A7%D9%81%D8%AA%20.pdf",
        "book": "motaleat",
        "boolInP": "مطالعات اجتماعی",
        "gradeInP": "پایه سوم",
        "category": "tarhedars",
        "image": "/images/hamyar/components/modules/books/sevom/motaleat.jpg",
        "slug": "/hamyar/sevom/tarhedars/32552"
      },
      {
        "id": 85472,
        "name": "طرح درس کار نیک - فارسی سوم",
        "caption": "طرح درس کار نیک - فارسی سوم - پایه سوم",
        "creator": "سرکار خانم شاه علی",
        "upoledDate": "1404/02/07",
        "fileType": "PDF",
        "src": "https://coding-lbf.storage.iran.liara.space/sevom/shahali/09/%D8%B7%D8%B1%D8%AD%20%D8%AF%D8%B1%D8%B3%20%DA%A9%D8%A7%D8%B1%20%D9%86%DB%8C%DA%A9%20-%20%D9%81%D8%A7%D8%B1%D8%B3%DB%8C%20%D8%B3%D9%88%D9%85.pdf",
        "book": "farsi",
        "boolInP": "فارسی",
        "gradeInP": "پایه سوم",
        "category": "tarhedars",
        "image": "/images/hamyar/components/modules/books/sevom/farsi.jpg",
        "slug": "/hamyar/sevom/tarhedars/85472"
      },
      {
        "id": 36553,
        "name": "طرح درس نیرو همه جا  - علوم تجربی",
        "caption": "طرح درس نیرو همه جا  - علوم تجربی - پایه سوم",
        "creator": "سرکار خانم شاه علی",
        "upoledDate": "1404/02/07",
        "fileType": "PDF",
        "src": "https://coding-lbf.storage.iran.liara.space/sevom/shahali/09/%D8%B7%D8%B1%D8%AD%20%D8%AF%D8%B1%D8%B3%20%D9%86%DB%8C%D8%B1%D9%88%20%D9%87%D9%85%D9%87%20%D8%AC%D8%A7%20%20-%20%D8%B9%D9%84%D9%88%D9%85%20%D8%AA%D8%AC%D8%B1%D8%A8%DB%8C.pdf",
        "book": "oloom",
        "boolInP": "علوم تجربی",
        "gradeInP": "پایه سوم",
        "category": "tarhedars",
        "image": "/images/hamyar/components/modules/books/sevom/oloom.jpg",
        "slug": "/hamyar/sevom/tarhedars/36553"
      },
      {
        "id": 99491,
        "name": "طرح درس مفهوم ضرب - ریاضی سوم",
        "caption": "طرخ درس مفهوم ضرب - ریاضی سوم - پایه سوم",
        "creator": "سرکار خانم شاه علی",
        "upoledDate": "1404/02/07",
        "fileType": "PDF",
        "src": "https://coding-lbf.storage.iran.liara.space/sevom/shahali/09/%D8%B7%D8%B1%D8%AE%20%D8%AF%D8%B1%D8%B3%20%D9%85%D9%81%D9%87%D9%88%D9%85%20%D8%B6%D8%B1%D8%A8%20-%20%D8%B1%DB%8C%D8%A7%D8%B6%DB%8C%20%D8%B3%D9%88%D9%85.pdf",
        "book": "riazi",
        "boolInP": "ریاضی",
        "gradeInP": "پایه سوم",
        "category": "tarhedars",
        "image": "/images/hamyar/components/modules/books/sevom/riazi.jpg",
        "slug": "/hamyar/sevom/tarhedars/99491"
      },
      {
        "id": 10252,
        "name": "طرح درس بازیافت - مطالعات اجتماعی",
        "caption": "طرح درس بازیافت - مطالعات اجتماعی - پایه سوم",
        "creator": "سرکار خانم شاه علی",
        "upoledDate": "1404/02/07",
        "fileType": "PDF",
        "src": "https://coding-lbf.storage.iran.liara.space/sevom/shahali/09/%D8%B7%D8%B1%D8%AD%20%D8%AF%D8%B1%D8%B3%20%D8%A8%D8%A7%D8%B2%DB%8C%D8%A7%D9%81%D8%AA%20-%20%D9%85%D8%B7%D8%A7%D9%84%D8%B9%D8%A7%D8%AA%20%D8%A7%D8%AC%D8%AA%D9%85%D8%A7%D8%B9%DB%8C.pdf",
        "book": "motaleat",
        "boolInP": "مطالعات اجتماعی",
        "gradeInP": "پایه سوم",
        "category": "tarhedars",
        "image": "/images/hamyar/components/modules/books/sevom/oloom.jpg",
        "slug": "/hamyar/sevom/tarhedars/10252"
      }


]

export default data